
package UIMainStream.DashBoard.navigation;

import UIMainStream.DashBoard.Component.*;

import UIMainStream.DashBoard.DashBoardContent;
import UIMainStream.DashBoard.DashBoardFrame;
import UIMainStream.MainEntry;
import java.awt.Color;

import javax.swing.ImageIcon;
import javax.swing.JScrollPane;

import Functions.ImageFunction;

/**
 *
 * @author DELL
 */
public class Navigation_Component extends javax.swing.JPanel {

    String name;

    public Navigation_Component(String name) {
        this.name = name;
        initComponents();
        initIcon();

        nameBtn.setText(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameBtn = new javax.swing.JLabel();
        iconBtn = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        nameBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nameBtn.setText("aaaaaaaaa");

        iconBtn.setText("        ");
        iconBtn.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(iconBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(nameBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nameBtn)
                                .addContainerGap())
                        .addComponent(iconBtn, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));
    }// </editor-fold>//GEN-END:initComponents

    private void initIcon() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/icon/" + name + "_Icon.png"));
        iconBtn.setSize(28, 28);
        iconBtn.setIcon(ImageFunction.scaleImage(iconBtn, icon));
    }

    private void formMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_formMouseEntered
        this.setBackground(new Color(204, 204, 255));
        nameBtn.setForeground(Color.white);
    }// GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_formMouseExited
        this.setBackground(Color.white);
        nameBtn.setForeground(Color.black);
    }// GEN-LAST:event_formMouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_formMouseClicked
        DashBoardContent.getInstance().removeAll();
        switch (name) {
            case "My Profile":
                DashBoardContent.getInstance().add(new User_Component());
                DashBoardContent.getInstance().repainting();
                System.out.println("directing to user page");

                break;
            case "Create Request":
                DashBoardContent.getInstance().add(new CreateRequest_Component());
                DashBoardContent.getInstance().repainting();
                System.out.println("directing to formt page");

                break;
            case "Requests":
                JScrollPane jScrollPane = new JScrollPane(new Request_Container());
                jScrollPane.getVerticalScrollBar().setUnitIncrement(10);
                DashBoardContent.getInstance().add(jScrollPane);
                DashBoardContent.getInstance().repainting();
                System.out.println("directing to request display page");

                break;
            case "Reports":
                JScrollPane jScrollPane1 = new JScrollPane(new Report_Container());
                jScrollPane1.getVerticalScrollBar().setUnitIncrement(10);
                DashBoardContent.getInstance().add(jScrollPane1);
                DashBoardContent.getInstance().repainting();
                System.out.println("directing to report display page");

                break;
            case "My Vehicles":
                JScrollPane jScrollPane2 = new JScrollPane(new Vehicles_Container());
                jScrollPane2.getVerticalScrollBar().setUnitIncrement(10);
                DashBoardContent.getInstance().add(jScrollPane2);
                DashBoardContent.getInstance().repainting();
                System.out.println("directing to vehicle display page");

                break;

            case "Logout":
                DashBoardFrame.getInstance().dispose();
                MainEntry.startUp();
                System.out.println("system log out:");

            default:
                throw new AssertionError();
        }
    }// GEN-LAST:event_formMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconBtn;
    private javax.swing.JLabel nameBtn;
    // End of variables declaration//GEN-END:variables
}
