
package UIMainStream.DashBoard.Component;

import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class CreateRequest_Component extends javax.swing.JPanel {

    /**
     * Creates new form Create_Component
     */
    public CreateRequest_Component() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        textname = new javax.swing.JTextField();
        birthday = new javax.swing.JLabel();
        textbirthday = new javax.swing.JTextField();
        vehicle = new javax.swing.JLabel();
        size = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();
        cancel = new javax.swing.JButton();
        create = new javax.swing.JButton();
        bienso = new javax.swing.JLabel();
        textbienso = new javax.swing.JTextField();
        Size = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        name.setText("Name");

        textname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        birthday.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        birthday.setText("Birthday");

        textbirthday.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        vehicle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        vehicle.setText("Type Vehicle");

        size.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        size.setText("Size");

        type.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "water", "lane", " " }));

        cancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancel.setText("Cancel");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });

        create.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        create.setText("Create ");
        create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createMouseClicked(evt);
            }
        });

        bienso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bienso.setText("Plate");

        textbienso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Size.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Size.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "small", "medium", "large" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(vehicle, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(110, 110, 110)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(textbirthday,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 184,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(textname,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 184,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(type,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 183,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(create)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(birthday)
                                                                        .addComponent(name)
                                                                        .addComponent(size,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                43,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(bienso,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                72,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(126, 126, 126)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(Size,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                183,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(textbienso,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                183,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(cancel)
                                                .addGap(309, 309, 309)))
                                .addContainerGap(169, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(name)
                                        .addComponent(textname, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(birthday)
                                        .addComponent(textbirthday, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(vehicle))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(size)
                                        .addComponent(Size, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bienso)
                                        .addComponent(textbienso, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cancel)
                                        .addComponent(create))
                                .addContainerGap(155, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void createMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_createMouseClicked
        JOptionPane.showMessageDialog(this, "Create Successfully");
        resetAllTextes();
    }// GEN-LAST:event_createMouseClicked

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_cancelMouseClicked
        JOptionPane.showMessageDialog(this, "Cancel Successfully");
        resetAllTextes();
    }// GEN-LAST:event_cancelMouseClicked

    public void resetAllTextes() {
        textname.setText("");
        textbirthday.setText("");
        textbienso.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Size;
    private javax.swing.JLabel bienso;
    private javax.swing.JLabel birthday;
    private javax.swing.JButton cancel;
    private javax.swing.JButton create;
    private javax.swing.JLabel name;
    private javax.swing.JLabel size;
    private javax.swing.JTextField textbienso;
    private javax.swing.JTextField textbirthday;
    private javax.swing.JTextField textname;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JLabel vehicle;
    // End of variables declaration//GEN-END:variables
}
