package UIMainStream.DashBoard.Component;

import javax.swing.ImageIcon;

import Functions.ImageFunction;
import Models.User;

/**
 * @author Pham Trung Duc
 * @author Huynh Kim Ai
 */
public class Empty_Screen extends javax.swing.JPanel {

    public Empty_Screen() {
        initComponents();
        secondStageinitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        satisticLabelPending = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        satisticLabelPending.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        if (User.getInstance().getAdminRight())
            satisticLabelPending.setText("Entire codebase is empty for now.");
        else
            satisticLabelPending.setText("This list of yours is empty for now.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(243, 243, 243)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(satisticLabelPending)
                                        .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(243, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(satisticLabelPending)
                                .addContainerGap(50, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void secondStageinitComponents() {
        initIcon();
    }

    private void initIcon() {
        ImageIcon emptyIcon = new ImageIcon(getClass().getResource("/icon/Empty_List_Icon.png"));
        icon.setSize(200, 200);
        icon.setIcon(ImageFunction.scaleImage(icon, emptyIcon));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icon;
    private javax.swing.JLabel satisticLabelPending;
    // End of variables declaration//GEN-END:variables
}
