/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UIMainStream.DashBoard.Component;

/**
 *
 * @author DELL
 */
public class Report_Component extends javax.swing.JPanel {

    /**
     * Creates new form Report
     */
    public Report_Component() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        bienso = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labeltype = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        requestedTime = new javax.swing.JLabel();
        labelreuqest = new javax.swing.JLabel();
        labelstatus = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        name.setText("Name");

        bienso.setText("Type Vehicle");

        status.setText("Status ");

        labelName.setText("jLabel8");

        labeltype.setText("jLabel11");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        requestedTime.setText("Requested Time");

        labelreuqest.setText("jLabel2");

        labelstatus.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bienso, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelName)
                            .addComponent(labeltype))
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(requestedTime)
                                .addGap(72, 72, 72)
                                .addComponent(labelreuqest))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(status)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelstatus)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(labelName)
                    .addComponent(requestedTime)
                    .addComponent(labelreuqest))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bienso)
                    .addComponent(labeltype)
                    .addComponent(status)
                    .addComponent(labelstatus))
                .addGap(264, 264, 264)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bienso;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelreuqest;
    private javax.swing.JLabel labelstatus;
    private javax.swing.JLabel labeltype;
    private javax.swing.JLabel name;
    private javax.swing.JLabel requestedTime;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
