package UIMainStream.DashBoard.Component;
/**
 * @author DELL
 */
public class Report_Component extends javax.swing.JPanel {

    public Report_Component() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelstatus2 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        bienso = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labeltype = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        requestedTime = new javax.swing.JLabel();
        labelreuqesttime = new javax.swing.JLabel();
        labelstatus = new javax.swing.JLabel();
        idReport = new javax.swing.JLabel();
        labelid = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        labelstatus2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelstatus2.setText("Drive in");

        name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        name.setText("Name");

        bienso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bienso.setText("Type Vehicle");

        status.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        status.setText("Status ");

        labelName.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelName.setText("userfull name");

        labeltype.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labeltype.setText("type");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        requestedTime.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        requestedTime.setText("Requested Time");

        labelreuqesttime.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelreuqesttime.setText("hh/dd/mm/yy");

        labelstatus.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelstatus.setText("on going");

        idReport.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        idReport.setText("Report ID");

        labelid.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelid.setText("0");

        confirmButton.setBackground(new java.awt.Color(102, 102, 102));
        confirmButton.setForeground(new java.awt.Color(255, 255, 255));
        confirmButton.setText("Confirm this Request is Finished");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(idReport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(requestedTime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bienso, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(labelName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                    .addComponent(labeltype, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(status)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labelstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelstatus2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(labelreuqesttime, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(status)
                    .addComponent(labelstatus)
                    .addComponent(labelstatus2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bienso)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labeltype, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requestedTime)
                    .addComponent(labelreuqesttime, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(confirmButton)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idReport)
                    .addComponent(labelid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bienso;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel idReport;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelid;
    private javax.swing.JLabel labelreuqesttime;
    private javax.swing.JLabel labelstatus;
    private javax.swing.JLabel labelstatus2;
    private javax.swing.JLabel labeltype;
    private javax.swing.JLabel name;
    private javax.swing.JLabel requestedTime;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
