package UIMainStream.DashBoard.Component;

import Models.DataBase;
import Models.Request;
import Models.Time;
import Models.User;
import Models.Vehicle;

/**
 * @author DELL
 * @author ACER
 */
public class Request_Component extends javax.swing.JPanel {
    public Request_Component() {
        initComponents();
    }

    public Request_Component(Request request) {
        initComponents();
        secondStageinitComponents(request);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        plate = new javax.swing.JLabel();
        request = new javax.swing.JLabel();
        size = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelBienso = new javax.swing.JLabel();
        labelSize = new javax.swing.JLabel();
        labelType = new javax.swing.JLabel();
        labelsubmit = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        requesttime = new javax.swing.JLabel();
        labelreqeusted = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        labelstatus = new javax.swing.JLabel();
        idRequest = new javax.swing.JLabel();
        labelID = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        name.setText("Name");

        plate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        plate.setText("Plate");

        request.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        request.setText("Type");

        size.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        size.setText("Size");

        date.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        date.setText("Submit Time");

        labelName.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelName.setText("jLabel10");

        labelBienso.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelBienso.setText("jLabel12");

        labelSize.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelSize.setText("jLabel13");

        labelType.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelType.setText("jLabel14");

        labelsubmit.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelsubmit.setText("jLabel15");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        requesttime.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        requesttime.setText("Requested Time");

        labelreqeusted.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelreqeusted.setText("jLabel2");

        status.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        status.setText("Status");

        labelstatus.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelstatus.setText("jLabel3");

        idRequest.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idRequest.setText("ID Request");

        labelID.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelID.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jSeparator1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(name)
                                                        .addComponent(plate)
                                                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 92,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(requesttime))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(labelreqeusted,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(labelBienso,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(labelName, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                231, Short.MAX_VALUE)
                                                        .addComponent(labelsubmit, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(idRequest, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                107, Short.MAX_VALUE)
                                                        .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(request, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(size, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(labelstatus, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(labelID, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(labelType, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(labelSize, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(19, 19, 19)))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(name)
                                                .addGap(29, 29, 29)
                                                .addComponent(plate)
                                                .addGap(33, 33, 33)
                                                .addComponent(requesttime)
                                                .addGap(27, 27, 27)
                                                .addComponent(date))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelName)
                                                .addGap(29, 29, 29)
                                                .addComponent(labelBienso)
                                                .addGap(33, 33, 33)
                                                .addComponent(labelreqeusted)
                                                .addGap(27, 27, 27)
                                                .addComponent(labelsubmit))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(size)
                                                                .addComponent(labelSize))
                                                        .addGap(29, 29, 29)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(labelType)
                                                                .addComponent(request))
                                                        .addGap(33, 33, 33)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(status)
                                                                .addComponent(labelstatus))
                                                        .addGap(45, 45, 45))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGap(147, 147, 147)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(labelID)
                                                                .addComponent(idRequest)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28,
                                        Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)));
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("unused")
    private void secondStageinitComponents(String userId, String id, String vehicleID,
            boolean isAccepted, Time requestedTime, Time submittedTime, String type, char size) {
        // I am thinking about sending in id and pull everything up, found the right doc
        // and update it here. but I already pull the entire thing in the mother
        // container, so I figure this is a huge waste of performance. let just take
        // needed data as params instead.
        labelName.setText(User.getInstance().getFullName());
        labelID.setText(id);
        if (isAccepted)
            labelstatus.setText("Accepted");
        else
            labelstatus.setText("Pending");
        labelBienso.setText(vehicleID);
        labelSize.setText(Character.toString(size));
        labelType.setText(type);
        labelreqeusted.setText(requestedTime.toString());
        labelsubmit.setText(submittedTime.toString());
    }

    private void secondStageinitComponents(Request request) {
        // create veh and add id
        Vehicle vehicle = new Vehicle(request.getVehicleID());
        DataBase.vormit(vehicle);// pull it from database

        labelName.setText(User.getInstance().getFullName());
        labelID.setText(request.getId());
        labelBienso.setText(vehicle.getVehicleLicensedPlate());

        labelSize.setText(Character.toString(vehicle.getSize()));
        labelType.setText(vehicle.getType().name());
        // get the object, as an enum it have .name()
        // that return a String name of the constant.

        labelreqeusted.setText(request.getRequestedTime().toString());
        labelsubmit.setText(request.getSubmittedTime().toString());

        if (request.getStatus())
            labelstatus.setText("Accepted");
        else
            labelstatus.setText("Pending");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JLabel idRequest;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelBienso;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelSize;
    private javax.swing.JLabel labelType;
    private javax.swing.JLabel labelreqeusted;
    private javax.swing.JLabel labelstatus;
    private javax.swing.JLabel labelsubmit;
    private javax.swing.JLabel name;
    private javax.swing.JLabel plate;
    private javax.swing.JLabel request;
    private javax.swing.JLabel requesttime;
    private javax.swing.JLabel size;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
