/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UIMainStream.DashBoard.Component;

/**
 *
 * @author DELL
 */
public class Request_Component extends javax.swing.JPanel {

    /**
     * Creates new form Request
     */
    public Request_Component() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        plate = new javax.swing.JLabel();
        request = new javax.swing.JLabel();
        size = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelBienso = new javax.swing.JLabel();
        labelSize = new javax.swing.JLabel();
        labelType = new javax.swing.JLabel();
        labelsubmit = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        requesttime = new javax.swing.JLabel();
        labelreqeusted = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        labelstatus = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        name.setText("Name");

        plate.setText("Plate");

        request.setText("Type");

        size.setText("Size");

        date.setText("Submit Time");

        labelName.setText("jLabel10");

        labelBienso.setText("jLabel12");

        labelSize.setText("jLabel13");

        labelType.setText("jLabel14");

        labelsubmit.setText("jLabel15");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        requesttime.setText("Requested Time");

        labelreqeusted.setText("jLabel2");

        status.setText("Status");

        labelstatus.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(plate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelBienso))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(name)
                        .addGap(69, 69, 69)
                        .addComponent(labelName))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelSize)))
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(request, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(labelType))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(requesttime)
                            .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelstatus)
                            .addComponent(labelsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelreqeusted, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(labelName)
                    .addComponent(request)
                    .addComponent(labelType))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date)
                    .addComponent(labelsubmit)
                    .addComponent(plate)
                    .addComponent(labelBienso))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(size)
                    .addComponent(labelSize)
                    .addComponent(requesttime)
                    .addComponent(labelreqeusted))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(status)
                    .addComponent(labelstatus))
                .addGap(80, 80, 80)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelBienso;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelSize;
    private javax.swing.JLabel labelType;
    private javax.swing.JLabel labelreqeusted;
    private javax.swing.JLabel labelstatus;
    private javax.swing.JLabel labelsubmit;
    private javax.swing.JLabel name;
    private javax.swing.JLabel plate;
    private javax.swing.JLabel request;
    private javax.swing.JLabel requesttime;
    private javax.swing.JLabel size;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
