/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UIMainStream.DashBoard.Component;

/**
 *
 * @author DELL
 */
public class Vehicles_Component extends javax.swing.JPanel {

    /**
     * Creates new form Vehicle1
     */
    public Vehicles_Component() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        bienso = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Vitridau = new javax.swing.JLabel();
        labelvitridau = new javax.swing.JLabel();
        labelsize = new javax.swing.JLabel();
        labeltype = new javax.swing.JLabel();
        labelbiéno = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        name.setText("Size");

        type.setBackground(new java.awt.Color(255, 255, 255));
        type.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        type.setText("Type Vehicle");

        bienso.setBackground(new java.awt.Color(255, 255, 255));
        bienso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bienso.setText("Plate");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        Vitridau.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Vitridau.setText("Place");

        labelvitridau.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelvitridau.setText("jLabel2");

        labelsize.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelsize.setText("jLabel1");

        labeltype.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labeltype.setText("jLabel3");

        labelbiéno.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        labelbiéno.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(type)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(name)
                            .addGap(74, 74, 74))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Vitridau, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bienso, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(45, 45, 45))))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labeltype, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(labelbiéno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelsize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelvitridau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(type)
                    .addComponent(labeltype))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(labelsize))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bienso)
                    .addComponent(labelbiéno))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Vitridau)
                    .addComponent(labelvitridau))
                .addGap(45, 45, 45)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Vitridau;
    private javax.swing.JLabel bienso;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelbiéno;
    private javax.swing.JLabel labelsize;
    private javax.swing.JLabel labeltype;
    private javax.swing.JLabel labelvitridau;
    private javax.swing.JLabel name;
    private javax.swing.JLabel type;
    // End of variables declaration//GEN-END:variables
}
