/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UIMainStream.DashBoard.Component;

/**
 *
 * @author DELL
 */
public class Vehicles_Component extends javax.swing.JPanel {

    /**
     * Creates new form Vehicle1
     */
    public Vehicles_Component() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        bienso = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Vitridau = new javax.swing.JLabel();
        labelvitridau = new javax.swing.JLabel();
        labelsize = new javax.swing.JLabel();
        labeltype = new javax.swing.JLabel();
        labelbiéno = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setText("Size");

        type.setBackground(new java.awt.Color(255, 255, 255));
        type.setText("Type Vehicle");

        bienso.setBackground(new java.awt.Color(255, 255, 255));
        bienso.setText("Plate");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        Vitridau.setText("Place");

        labelvitridau.setText("jLabel2");

        labelsize.setText("jLabel1");

        labeltype.setText("jLabel3");

        labelbiéno.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name)
                    .addComponent(type))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labeltype)
                    .addComponent(labelsize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bienso, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Vitridau, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelvitridau, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelbiéno))
                .addContainerGap(134, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(labelsize)
                    .addComponent(bienso)
                    .addComponent(labelbiéno))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(type)
                    .addComponent(labeltype)
                    .addComponent(Vitridau)
                    .addComponent(labelvitridau))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Vitridau;
    private javax.swing.JLabel bienso;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelbiéno;
    private javax.swing.JLabel labelsize;
    private javax.swing.JLabel labeltype;
    private javax.swing.JLabel labelvitridau;
    private javax.swing.JLabel name;
    private javax.swing.JLabel type;
    // End of variables declaration//GEN-END:variables
}
